#!/usr/bin/env python3
"""mythril.py: Bug hunting on the Ethereum blockchain
   http://www.github.com/b-mueller/mythril
   """
from mythril import __main__

if __name__ == "__main__":
    __main__.main()
