#!/usr/bin/env python
"""mythril.py: Smart contract bug hunting on the Ethereum blockchain

   http://www.github.com/b-mueller/mythril
"""

from ether import asm,evm,util
from contractstorage import ContractStorage
import sys
import codecs
import argparse


def exitWithError(message):
    print(message)
    sys.exit()


parser = argparse.ArgumentParser(description='Smart contract bug hunting on the Ethereum blockchain')

parser.add_argument('-d', '--disassemble',  action='store_true', help='disassemble, use with -c or --id')
parser.add_argument('-t', '--trace',  action='store_true', help='trace contract code provided via the -c or --id argument')
parser.add_argument('-c', '--code', help='hex-encoded bytecode string ("6060604052...")', metavar='BYTECODE')
parser.add_argument('-o', '--outfile')
parser.add_argument('--id', help='contract id')
parser.add_argument('--init-db', action='store_true', help='Initialize the contract database')
parser.add_argument('--search', help='search contract database')
parser.add_argument('--rpchost', default='127.0.0.1', help='RPC host')
parser.add_argument('--rpcport', type=int, default=8545, help='RPC port')


storage = ContractStorage()


args = parser.parse_args()

if (args.disassemble):

    if (args.code):
        encoded_bytecode = args.code
    elif (args.id):

        try:
            encoded_bytecode = storage.get_contract_code_by_address(args.id)

        except Exception as e:
            exitWithError("Exception loading bytecode via RPC: " + str(e))

    elif (args.infile):

        try:

            encoded_bytecode = util.file_to_string(args.infile).rstrip()

        except Exception as e:
            exitWithError("Exception loading bytecode from file: " + str(e))

    else:
        exitWithError("Disassembler: Provide the input bytecode via -c BYTECODE, -f INPUT_FILE or --txid TXID")

    disassembly = asm.disassemble(util.safe_decode(encoded_bytecode))

    easm_text = asm.disassembly_to_easm(disassembly)

    if (args.outfile):
        util.string_to_file(args.outfile, easm_text)
    else:
        sys.stdout.write(easm_text)

elif (args.trace):

    if args.code:     

        bytecode = util.safe_decode(args.code)

    elif (args.infile):

        try:

            bytecode = util.file_to_raw_bytes(args.infile)

        except FileNotFoundError:
            exitWithError("Error loading bytecode: Input file not found")

    else:
        exitWithError("Trace: Provide the input bytecode using -c BYTECODE or -f INPUT_FILE")

    evm.trace(bytecode)

elif (args.search):

    storage.search(args.search)

elif (args.init_db):
        storage.initialize(args.rpchost, args.rpcport)  

else:
    parser.print_help()
